### ISSUE TITLE
SPI 1

### ISSUE THREAD

**Issue by ToninoTarsi** [Inteform/PyLora#1]
Hi,
I would like to use spi1 channel   (gpio16,19,20,21) instead of spi0 channel.
How to configure it with PyLora.set_pins() ?
Thanks

**Comment by bruabas** [comment]
Ciao Tonino,
You can change the pins using the function
```python
PyLora.set_pins(spi_device="/dev/spidev0.0", cs_pin=25, rst_pin=17)
```
those are the default values. You shall call it with the desired values,
```python
PyLora.set_pins(spi_device="/dev/spidev1.0", cs_pin=16, rst_pin=17)
PyLora.init()
```
-- don't forget your RST pin.
The spidev driver must be available for channel 1. The linux `spidev` driver is quite nice, you can even configure it to use other pins as a software SPI device.

**Comment by bruabas** [comment]
Sorry, I closed the issue by accident... !

**Comment by ToninoTarsi** [comment]
Thanks Bruno,
I will use your work in my weather station project ( https://github.com/ToninoTarsi/swpi )
Thanks for your work
Tonino

**Comment by ToninoTarsi** [comment]
sorry ,
I just reopen for a small further question. In the documentation I can found:

Pin | Signal
-- | --
CS | GPIO25
RST | GPIO17
MISO | GPIO9
MOSI | GPIO10
SCK | GPIO11

But according to Raspberry PI documentation hardware CS0 pin is GPIO8 and not GPIO25 ( https://pinout.xyz/pinout/spi# )

So I suppose that if I want to stick with the default Raspberry PI pins using device 0 I have to use: 

`PyLora.set_pins(spi_device="/dev/spidev0.0", cs_pin=8, rst_pin=17)`
 
Is that correct ?
Thanks

**Comment by bruabas** [comment]
Hi Tonino
Indeed, yes. This default pattern of pins is because the hat we are using has the GPIO25 connected to the CS.
The library does not use automatic chip-selects of spidev, so you can stick with any pin you want; this is useful also for boards other than the Raspberry Pi that have only one hardwired CS channel.
Do you believe it would be better to change the default setup?
Nice project you have in there! Congrats!
Thanks

**Comment by ToninoTarsi** [comment]
Thanks Bruno,
No problem. Indeed your library is more generic and not only related to Raspberry so no need to modify.
I will initialize according to RPI default PIN.
Thanks

**Comment by atonughosh** [comment]
I get this error 
```
Traceback (most recent call last):
  File "send.py", line 5, in <module>
    PyLora.set_frequency(433000000)
RuntimeError: Lora not initialized

```
with this code

```
import PyLora
import time
PyLora.set_pins(spi_device="/dev/spidev0.0", cs_pin=8, rst_pin=22)
PyLora.init()
PyLora.set_frequency(433000000)
PyLora.enable_crc()
while True:
    PyLora.receive()   # put into receive mode
    while not PyLora.packet_available():
        # wait for a package
        time.sleep(0)
    rec = PyLora.receive_packet()
    print 'Packet received: {}'.format(rec)
```

please help
