### ISSUE TITLE
Compile on Raspberry PI 

### ISSUE THREAD

**Issue by ToninoTarsi** [Inteform/PyLora#2]
To compile on raspberry PI I had yo add -std=c99 on CFLAGS either  using :

`CFLAGS="-std=c99" python setup.py build`

or modifying setup.py 

```
from distutils.core import setup, Extension


mod = Extension("PyLora",
                sources = ["src/PyLora.c",
                           "src/lora.c",
                           "src/gpio.c",
                           "src/spi.c"],
                           extra_compile_args = ["-std=c99"],
                include_dirs = ["./include"])

setup(
    name = "PyLora",
    version = "1.0",
    description = "Python interface with LoRa Radio Transceiver",
    author = "Bruno Abrantes Basseto",
    author_email = "bruno.basseto@inteform.com.br",
    url = "https://",
    ext_modules = [mod])
```

**Comment by bruabas** [comment]
This is **very** strange... I can compile it well without c99 language switch.
My compiler is
`gcc (Raspbian 6.3.0-18+rpi1) 6.3.0 20170516`
Is it possible that you are using clang instead?
Anyway, it is best to change setup.py script to explicitly setup the C dialect.
