### ISSUE TITLE
set_frequency

### ISSUE THREAD

**Issue by ToninoTarsi** [Inteform/PyLora#3]
On my Raspberry Pi Zero if I try to follow the snipped code in the Readme.md I got :

`pi@swpi ~/swpi/test_lora $ sudo python
Python 2.7.3 (default, Jun 22 2016, 03:14:32)
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import PyLora
>>> PyLora.init()
1
>>> PyLora.set_frequency(915e6)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: integer argument expected, got float
`

Casting :  

`PyLora.set_frequency(int(915e6))`

Works fine but I do not know yet the result as I'm still waiting for my RFM95 module.

Thanks

**Comment by bruabas** [comment]
Yep. Oops. Sorry. Thanks.
I copied the C++ example, ended up with a buggy example in README. Just changed it.
Use an integer and all is fine.
